#
# Component Makefile
#

# libssh
COMPONENT_SRCDIRS += ./libssh/src
COMPONENT_SRCDIRS += ./libssh/src/external
COMPONENT_SRCDIRS += ./libssh/src/threads
COMPONENT_SRCDIRS += ./libssh-esp8266
COMPONENT_ADD_INCLUDEDIRS += ./libssh-esp8266
COMPONENT_ADD_INCLUDEDIRS += ./libssh/include

CFLAGS += -DPACKAGE="libssh"
CFLAGS += -DFALL_THROUGH="__attribute__ ((fallthrough))"
CFLAGS += -DSSH_MALLOC\(a\)=pvPortMalloc\(a\)
CFLAGS += -DSSH_CALLOC\(a,b\)=pvPortCalloc\(a,b\)
CFLAGS += -DSSH_REALLOC\(a,b\)=pvPortRealloc\(a,b\)
CFLAGS += -DSSH_FREE\(a\)=vPortFree\(a\)
CFLAGS += -DSYSCONFDIR="/"
CFLAGS += -DBINARYDIR="libssh"
CFLAGS += -DSOURCEDIR="libssh"
CFLAGS += -DSSH_BUFFER_SIZE_MAX=esp_get_free_heap_size\(\)
CFLAGS += -DGLOBAL_BIND_CONFIG="\"libssh_server_config\""
CFLAGS += -DGLOBAL_CLIENT_CONFIG="\"ssh_config\""
CFLAGS += -DHAVE_ARGP_H=1
CFLAGS += -DHAVE_ARPA_INET_H=1
CFLAGS += -DHAVE_GLOB_H=1
CFLAGS += -DHAVE_UTMP_H=1
CFLAGS += -DHAVE_UTIL_H=1
CFLAGS += -DHAVE_SYS_TIME_H=1
CFLAGS += -DHAVE_TERMIOS_H=1
CFLAGS += -DHAVE_UNISTD_H=1
CFLAGS += -DHAVE_STDINT_H=1
CFLAGS += -DHAVE_ECC=1
CFLAGS += -DHAVE_GLOB_GL_FLAGS_MEMBER=1
CFLAGS += -DHAVE_SNPRINTF=1
CFLAGS += -DHAVE_VSNPRINTF=1
CFLAGS += -DHAVE_ISBLANK=1
CFLAGS += -DHAVE_STRNCPY=1
CFLAGS += -DHAVE_STRNDUP=1
CFLAGS += -DHAVE_CFMAKERAW=1
CFLAGS += -DHAVE_GETADDRINFO=1
CFLAGS += -DHAVE_POLL=1
CFLAGS += -DHAVE_SELECT=1
CFLAGS += -DHAVE_CLOCK_GETTIME=1
CFLAGS += -DHAVE_STRTOULL=1
CFLAGS += -DHAVE_GLOB=1
CFLAGS += -DHAVE_LIBMBEDCRYPTO=1
CFLAGS += -DHAVE_GCC_THREAD_LOCAL_STORAGE=1
CFLAGS += -DHAVE_FALLTHROUGH_ATTRIBUTE=1
CFLAGS += -DHAVE_UNUSED_ATTRIBUTE=1
CFLAGS += -DHAVE_CONSTRUCTOR_ATTRIBUTE=1
CFLAGS += -DHAVE_DESTRUCTOR_ATTRIBUTE=1
CFLAGS += -DHAVE_GCC_VOLATILE_MEMORY_PROTECTION=1
CFLAGS += -DHAVE_COMPILER__FUNC__=1
CFLAGS += -DHAVE_COMPILER__FUNCTION__=1
CFLAGS += -DWITH_SERVER=1
CFLAGS += -DWITH_GEX=1
CFLAGS += -DDEBUG_CRYPTO=1
CFLAGS += -DDEBUG_PACKET=1
CFLAGS += -DDEBUG_CALLTRACE=1
CFLAGS += -DDEBUG_BUFFER=1
CFLAGS += -DNI_MAXHOST=1
CFLAGS += -Wno-format
###############

# sshd
COMPONENT_SRCDIRS += ./sshd
COMPONENT_ADD_INCLUDEDIRS += ./sshd
###############
